#!/bin/sh
#
# PROVIDE: xray_webui
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable xray-webui:
# xray_webui_enable="YES"

. /etc/rc.subr

name="xray_webui"
rcvar="xray_webui_enable"

load_rc_config $name

: ${xray_webui_enable="NO"}

command="/usr/sbin/daemon"
pidfile="/var/run/xray-webui.pid"
xray_webui_command="/usr/local/bin/xray run -config /usr/local/etc/xray-webui/config.json"
command_args="-c -f -o /var/log/xray-webui.log -P ${pidfile} ${xray_webui_command}"

export XRAY_LOCATION_ASSET="/usr/local/share/xray"

run_rc_command "$1"
