[start]
command:sh /usr/local/etc/rc.d/xray-webui start
parameters:
type:script
message:starting xray-webui

[stop]
command:sh /usr/local/etc/rc.d/xray-webui stop
parameters:
type:script
message:stopping xray-webui

[restart]
command:sh /usr/local/etc/rc.d/xray-webui restart
parameters:
type:script
message:restarting xray-webui

[status]
command:sh /usr/local/etc/rc.d/xray-webui status
parameters:
type:script_output
message:request xray-webui status
