[start]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel start
parameters:
type:script
message:starting tun2socks

[stop]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel stop
parameters:
type:script
message:stopping tun2socks

[restart]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel restart
parameters:
type:script
message:restarting tun2socks
description:Restart tun2socks (hev-socks5-tunnel) service

[status]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel status
parameters:
type:script_output
message:request tun2socks status
