[start]
command:sh /usr/local/etc/rc.d/v2raya start
parameters:
type:script
message:starting v2raya

[stop]
command:sh /usr/local/etc/rc.d/v2raya stop
parameters:
type:script
message:stopping v2raya

[restart]
command:sh /usr/local/etc/rc.d/v2raya restart
parameters:
type:script
message:restarting v2raya
description:Restart v2rayA service

[status]
command:sh /usr/local/etc/rc.d/v2raya status
parameters:
type:script_output
message:request v2raya status

[tunnel-start]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel start
parameters:
type:script
message:starting hev-socks5-tunnel

[tunnel-stop]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel stop
parameters:
type:script
message:stopping hev-socks5-tunnel

[tunnel-restart]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel restart
parameters:
type:script
message:restarting hev-socks5-tunnel
description:Restart hev-socks5-tunnel service

[tunnel-status]
command:sh /usr/local/etc/rc.d/hevsocks5tunnel status
parameters:
type:script_output
message:request hev-socks5-tunnel status
